import { IsUUID, IsNotEmpty } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class CreatePaymentIntentDto {
  @ApiProperty({ example: 'a5c8df41-1191-4e7d-965b-bf4e5659828d', description: 'The unique ID of the event' })
  @IsUUID()
  @IsNotEmpty()
  eventId: string;
}

export class PaymentIntentResponseDto {
  @ApiProperty({
    description: 'The payment gateway URL where the user will complete the transaction securely',
    example: 'https://checkout.paystack.com/7v89w01x2y3z'
  })
  authorization_url: string;

  @ApiProperty({
    description: 'Unique reference identifier generated by Paystack for tracking this transaction',
    example: 'EVT-7849102-XYZ'
  })
  reference: string;
}